 /** mock **/
(function(){
	"use strict";

	var app = angular
				.module("productResourceMock",
						["ngMockE2E"]);
	
	app.run(function ($httpBackend){
		//chords collection
		var chords = [
			{"chordId": 1,
			 "chordName": "maj",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_A.png",
			 "sharpUrl": "images/chords/Ukulele_AsharpBflat.png",
			 "flatUrl": "images/chords/Ukulele_GsharpAflat.png"
			},
			{"chordId": 2,
			 "chordName": "min",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Am.png",
			 "sharpUrl": "images/chords/Ukulele_AmsharpBmflat.png",
			 "flatUrl": "images/chords/Ukulele_GmsharpAmflat.png"
			},
			{"chordId": 3,
			 "chordName": "7th",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_A7.png",
			 "sharpUrl": "images/chords/Ukulele_A7sharpB7flat.png",
			 "flatUrl": "images/chords/Ukulele_G7sharpA7flat.png"
			},
			{"chordId": 4,
			 "chordName": "sus",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Asus.png",
			 "sharpUrl": "images/chords/Ukulele_AsussharpBsusflat.png",
			 "flatUrl": "images/chords/Ukulele_GsussharpAsusflat.png"
			},
			{"chordId": 5,
			 "chordName": "maj7",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Amaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Amaj7sharpBmaj7flat.png",
			 "flatUrl": "images/chords/Ukulele_Gmaj7sharpAmaj7flat.png"
			},
			{"chordId": 6,
			 "chordName": "min7",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Am7.png",
			 "sharpUrl": "images/chords/Ukulele_Am7sharpBm7flat.png",
			 "flatUrl": "images/chords/Ukulele_Gm7sharpAm7flat.png"
			},
			{"chordId": 7,
			 "chordName": "7sus",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_A7sus.png",
			 "sharpUrl": "images/chords/Ukulele_A7sussharpB7susflat.png",
			 "flatUrl": "images/chords/Ukulele_G7sussharpA7susflat.png"
			},
			{"chordId": 8,
			 "chordName": "9th",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_A9.png",
			 "sharpUrl": "images/chords/Ukulele_A9sharpB9flat.png",
			 "flatUrl": "images/chords/Ukulele_G9sharpA9flat.png"
			},
			{"chordId": 9,
			 "chordName": "inv-1",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Ainv1.png",
			 "sharpUrl": "images/chords/Ukulele_Ainv1sharpBinv1flat.png",
			 "flatUrl": "images/chords/Ukulele_Ginv1sharpAinv1flat.png"
			},
			{"chordId": 10,
			 "chordName": "inv-2",
			 "chordGroup": "A",
			 "imageUrl": "images/chords/Ukulele_Ainv2.png",
			 "sharpUrl": "images/chords/Ukulele_Ainv2sharpBinv2flat.png",
			 "flatUrl": "images/chords/Ukulele_Ginv2sharpAinv2flat.png"
			},
			{"chordId": 11,
			 "chordName": "maj",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_B.png",
			 "sharpUrl": "images/chords/Ukulele_C.png",
			 "flatUrl": "images/chords/Ukulele_AsharpBflat.png"
			},
			{"chordId": 12,
			 "chordName": "min",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Bm.png",
			 "sharpUrl": "images/chords/Ukulele_Cm.png",
			 "flatUrl": "images/chords/Ukulele_AmsharpBmflat.png"
			},
			{"chordId": 13,
			 "chordName": "7th",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_B7.png",
			 "sharpUrl": "images/chords/Ukulele_C7.png",
			 "flatUrl": "images/chords/Ukulele_A7sharpB7flat.png"
			},
			{"chordId": 14,
			 "chordName": "sus",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Bsus.png",
			 "sharpUrl": "images/chords/Ukulele_Csus.png",
			 "flatUrl": "images/chords/Ukulele_AsussharpBsusflat.png"
			},
			{"chordId": 15,
			 "chordName": "maj7",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Bmaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Cmaj7.png",
			 "flatUrl": "images/chords/Ukulele_Amaj7sharpBmaj7flat.png"
			},
			{"chordId": 16,
			 "chordName": "min7",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Bm7.png",
			 "sharpUrl": "images/chords/Ukulele_Cm7.png",
			 "flatUrl": "images/chords/Ukulele_Am7sharpBm7flat.png"
			},
			{"chordId": 17,
			 "chordName": "7sus",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_B7sus.png",
			 "sharpUrl": "images/chords/Ukulele_C7sus.png",
			 "flatUrl": "images/chords/Ukulele_A7sussharpB7susflat.png"
			},
			{"chordId": 18,
			 "chordName": "9th",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_B9.png",
			 "sharpUrl": "images/chords/Ukulele_C9.png",
			 "flatUrl": "images/chords/Ukulele_A9sharpB9flat.png"
			},
			{"chordId": 19,
			 "chordName": "inv-1",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Binv1.png",
			 "sharpUrl": "images/chords/Ukulele_Cinv1.png",
			 "flatUrl": "images/chords/Ukulele_Ainv1sharpBinv1flat.png"
			},
			{"chordId": 20,
			 "chordName": "inv-2",
			 "chordGroup": "B",
			 "imageUrl": "images/chords/Ukulele_Binv2.png",
			 "sharpUrl": "images/chords/Ukulele_Cinv2.png",
			 "flatUrl": "images/chords/Ukulele_Ainv2sharpBinv2flat.png"
			},
			{"chordId": 21,
			 "chordName": "maj",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_C.png",
			 "sharpUrl": "images/chords/Ukulele_CsharpDflat.png",
			 "flatUrl": "images/chords/Ukulele_B.png"
			},
			{"chordId": 22,
			 "chordName": "min",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Cm.png",
			 "sharpUrl": "images/chords/Ukulele_CmsharpDmflat.png",
			 "flatUrl": "images/chords/Ukulele_Bm.png"
			},
			{"chordId": 23,
			 "chordName": "7th",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_C7.png",
			 "sharpUrl": "images/chords/Ukulele_C7sharpD7flat.png",
			 "flatUrl": "images/chords/Ukulele_B7.png"
			},
			{"chordId": 24,
			 "chordName": "sus",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Csus.png",
			 "sharpUrl": "images/chords/Ukulele_CsussharpDsusflat.png",
			 "flatUrl": "images/chords/Ukulele_Bsus.png"
			},
			{"chordId": 25,
			 "chordName": "maj7",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Cmaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Cmaj7sharpDmaj7flat.png",
			 "flatUrl": "images/chords/Ukulele_Bmaj7.png"
			},
			{"chordId": 26,
			 "chordName": "min7",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Cm7.png",
			 "sharpUrl": "images/chords/Ukulele_Cm7sharpDm7flat.png",
			 "flatUrl": "images/chords/Ukulele_Bm7.png"
			},
			{"chordId": 27,
			 "chordName": "7sus",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_C7sus.png",
			 "sharpUrl": "images/chords/Ukulele_C7sussharpD7susflat.png",
			 "flatUrl": "images/chords/Ukulele_B7sus.png"
			},
			{"chordId": 28,
			 "chordName": "9th",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_C9.png",
			 "sharpUrl": "images/chords/Ukulele_C9sharpD9flat.png",
			 "flatUrl": "images/chords/Ukulele_B9.png"
			},
			{"chordId": 29,
			 "chordName": "inv-1",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Cinv1.png",
			 "sharpUrl": "images/chords/Ukulele_Cinv1sharpDinv1flat.png",
			 "flatUrl": "images/chords/Ukulele_Binv1.png"
			},
			{"chordId": 30,
			 "chordName": "inv-2",
			 "chordGroup": "C",
			 "imageUrl": "images/chords/Ukulele_Cinv2.png",
			 "sharpUrl": "images/chords/Ukulele_Cinv2sharpDinv2flat.png",
			 "flatUrl": "images/chords/Ukulele_Binv2.png"
			},
			{"chordId": 31,
			 "chordName": "maj",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_D.png",
			 "sharpUrl": "images/chords/Ukulele_DsharpEflat.png",
			 "flatUrl": "images/chords/Ukulele_CsharpDflat.png"
			},
			{"chordId": 32,
			 "chordName": "min",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dm.png",
			 "sharpUrl": "images/chords/Ukulele_DmsharpEmflat.png",
			 "flatUrl": "images/chords/Ukulele_CmsharpDmflat.png"
			},
			{"chordId": 33,
			 "chordName": "7th",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_D7.png",
			 "sharpUrl": "images/chords/Ukulele_D7sharpE7flat.png",
			 "flatUrl": "images/chords/Ukulele_C7sharpD7flat.png"
			},
			{"chordId": 34,
			 "chordName": "sus",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dsus.png",
			 "sharpUrl": "images/chords/Ukulele_DsussharpEsusflat.png",
			 "flatUrl": "images/chords/Ukulele_CsussharpDsusflat.png"
			},
			{"chordId": 35,
			 "chordName": "maj7",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dmaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Dmaj7sharpEmaj7flat.png",
			 "flatUrl": "images/chords/Ukulele_Cmaj7sharpDmaj7flat.png"
			},
			{"chordId": 36,
			 "chordName": "min7",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dm7.png",
			 "sharpUrl": "images/chords/Ukulele_Dm7sharpEm7flat.png",
			 "flatUrl": "images/chords/Ukulele_Cm7sharpDm7flat.png"
			},
			{"chordId": 37,
			 "chordName": "7sus",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_D7sus.png",
			 "sharpUrl": "images/chords/Ukulele_D7sussharpE7susflat.png",
			 "flatUrl": "images/chords/Ukulele_C7sussharpD7susflat.png"
			},
			{"chordId": 38,
			 "chordName": "9th",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_D9.png",
			 "sharpUrl": "images/chords/Ukulele_D9sharpE9flat.png",
			 "flatUrl": "images/chords/Ukulele_C9sharpD9flat.png"
			},
			{"chordId": 39,
			 "chordName": "inv-1",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dinv1.png",
			 "sharpUrl": "images/chords/Ukulele_Dinv1sharpEinv1flat.png",
			 "flatUrl": "images/chords/Ukulele_Cinv1sharpDinv1flat.png"
			},
			{"chordId": 40,
			 "chordName": "inv-2",
			 "chordGroup": "D",
			 "imageUrl": "images/chords/Ukulele_Dinv2.png",
			 "sharpUrl": "images/chords/Ukulele_Dinv2sharpEinv2flat.png",
			 "flatUrl": "images/chords/Ukulele_Cinv2sharpDinv2flat.png"
			},
			{"chordId": 41,
			 "chordName": "maj",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_E.png",
			 "sharpUrl": "images/chords/Ukulele_F.png",
			 "flatUrl": "images/chords/Ukulele_DsharpEflat.png"
			},
			{"chordId": 42,
			 "chordName": "min",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Em.png",
			 "sharpUrl": "images/chords/Ukulele_Fm.png",
			 "flatUrl": "images/chords/Ukulele_DmsharpEmflat.png"
			},
			{"chordId": 43,
			 "chordName": "7th",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_E7.png",
			 "sharpUrl": "images/chords/Ukulele_F7.png",
			 "flatUrl": "images/chords/Ukulele_D7sharpE7flat.png"
			},
			{"chordId": 44,
			 "chordName": "sus",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Esus.png",
			 "sharpUrl": "images/chords/Ukulele_Fsus.png",
			 "flatUrl": "images/chords/Ukulele_DsussharpEsusflat.png"
			},
			{"chordId": 45,
			 "chordName": "maj7",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Emaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Fmaj7.png",
			 "flatUrl": "images/chords/Ukulele_Dmaj7sharpEmaj7flat.png"
			},
			{"chordId": 46,
			 "chordName": "min7",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Em7.png",
			 "sharpUrl": "images/chords/Ukulele_Fm7.png",
			 "flatUrl": "images/chords/Ukulele_Dm7sharpEm7flat.png"
			},
			{"chordId": 47,
			 "chordName": "7sus",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_E7sus.png",
			 "sharpUrl": "images/chords/Ukulele_F7sus.png",
			 "flatUrl": "images/chords/Ukulele_D7sussharpE7susflat.png"
			},
			{"chordId": 48,
			 "chordName": "9th",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_E9.png",
			 "sharpUrl": "images/chords/Ukulele_F9.png",
			 "flatUrl": "images/chords/Ukulele_D9sharpE9flat.png"
			},
			{"chordId": 49,
			 "chordName": "inv-1",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Einv1.png",
			 "sharpUrl": "images/chords/Ukulele_Finv1.png",
			 "flatUrl": "images/chords/Ukulele_Dinv1sharpEinv1flat.png"
			},
			{"chordId": 50,
			 "chordName": "inv-2",
			 "chordGroup": "E",
			 "imageUrl": "images/chords/Ukulele_Einv2.png",
			 "sharpUrl": "images/chords/Ukulele_Finv2.png",
			 "flatUrl": "images/chords/Ukulele_Dinv2sharpEinv2flat.png"
			},
			{"chordId": 51,
			 "chordName": "maj",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_F.png",
			 "sharpUrl": "images/chords/Ukulele_FsharpGflat.png",
			 "flatUrl": "images/chords/Ukulele_E.png"
			},
			{"chordId": 52,
			 "chordName": "min",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Fm.png",
			 "sharpUrl": "images/chords/Ukulele_FmsharpGmflat.png",
			 "flatUrl": "images/chords/Ukulele_Em.png"
			},
			{"chordId": 53,
			 "chordName": "7th",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_F7.png",
			 "sharpUrl": "images/chords/Ukulele_F7sharpG7flat.png",
			 "flatUrl": "images/chords/Ukulele_E7.png"
			},
			{"chordId": 54,
			 "chordName": "sus",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Fsus.png",
			 "sharpUrl": "images/chords/Ukulele_FsussharpGsusflat.png",
			 "flatUrl": "images/chords/Ukulele_Esus.png"
			},
			{"chordId": 55,
			 "chordName": "maj7",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Fmaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Fmaj7sharpGmaj7flat.png",
			 "flatUrl": "images/chords/Ukulele_Emaj7.png"
			},
			{"chordId": 56,
			 "chordName": "min7",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Fm7.png",
			 "sharpUrl": "images/chords/Ukulele_Fm7sharpGm7flat.png",
			 "flatUrl": "images/chords/Ukulele_Em7.png"
			},
			{"chordId": 57,
			 "chordName": "7sus",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_F7sus.png",
			 "sharpUrl": "images/chords/Ukulele_F7sussharpG7susflat.png",
			 "flatUrl": "images/chords/Ukulele_E7sus.png"
			},
			{"chordId": 58,
			 "chordName": "9th",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_F9.png",
			 "sharpUrl": "images/chords/Ukulele_F9sharpG9flat.png",
			 "flatUrl": "images/chords/Ukulele_E9.png"
			},
			{"chordId": 59,
			 "chordName": "inv-1",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Finv1.png",
			 "sharpUrl": "images/chords/Ukulele_Finv1sharpGinv1flat.png",
			 "flatUrl": "images/chords/Ukulele_Einv1.png"
			},
			{"chordId": 60,
			 "chordName": "inv-2",
			 "chordGroup": "F",
			 "imageUrl": "images/chords/Ukulele_Finv2.png",
			 "sharpUrl": "images/chords/Ukulele_Finv2sharpGinv2flat.png",
			 "flatUrl": "images/chords/Ukulele_Einv2.png"
			},
			{"chordId": 61,
			 "chordName": "maj",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_G.png",
			 "sharpUrl": "images/chords/Ukulele_GsharpAflat.png",
			 "flatUrl": "images/chords/Ukulele_FsharpGflat.png"
			},
			{"chordId": 62,
			 "chordName": "min",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Gm.png",
			 "sharpUrl": "images/chords/Ukulele_GmsharpAmflat.png",
			 "flatUrl": "images/chords/Ukulele_FmsharpGmflat.png"
			},
			{"chordId": 63,
			 "chordName": "7th",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_G7.png",
			 "sharpUrl": "images/chords/Ukulele_G7sharpA7flat.png",
			 "flatUrl": "images/chords/Ukulele_F7sharpG7flat.png"
			},
			{"chordId": 64,
			 "chordName": "sus",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Gsus.png",
			 "sharpUrl": "images/chords/Ukulele_GsussharpAsusflat.png",
			 "flatUrl": "images/chords/Ukulele_FsussharpGsusflat.png"
			},
			{"chordId": 65,
			 "chordName": "maj7",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Gmaj7.png",
			 "sharpUrl": "images/chords/Ukulele_Gmaj7sharpAmaj7flat.png",
			 "flatUrl": "images/chords/Ukulele_Fmaj7sharpGmaj7flat.png"
			},
			{"chordId": 66,
			 "chordName": "min7",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Gm7.png",
			 "sharpUrl": "images/chords/Ukulele_Gm7sharpAm7flat.png",
			 "flatUrl": "images/chords/Ukulele_Fm7sharpGm7flat.png"
			},
			{"chordId": 67,
			 "chordName": "7sus",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_G7sus.png",
			 "sharpUrl": "images/chords/Ukulele_G7sussharpA7susflat.png",
			 "flatUrl": "images/chords/Ukulele_F7sussharpG7susflat.png"
			},
			{"chordId": 68,
			 "chordName": "9th",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_G9.png",
			 "sharpUrl": "images/chords/Ukulele_G9sharpA9flat.png",
			 "flatUrl": "images/chords/Ukulele_F9sharpG9flat.png"
			},
			{"chordId": 69,
			 "chordName": "inv-1",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Ginv1.png",
			 "sharpUrl": "images/chords/Ukulele_Ginv1sharpAinv1flat.png",
			 "flatUrl": "images/chords/Ukulele_Finv1sharpGinv1flat.png"
			},
			{"chordId": 70,
			 "chordName": "inv-2",
			 "chordGroup": "G",
			 "imageUrl": "images/chords/Ukulele_Ginv2.png",
			 "sharpUrl": "images/chords/Ukulele_Ginv2sharpAinv2flat.png",
			 "flatUrl": "images/chords/Ukulele_Finv2sharpGinv2flat.png"
			}
		];
		
		//progressions collection		
		var progressions = [
			{"progId": 1,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_D.png",
			 "imageUrl3": "images/chords/Ukulele_E.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 2,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl2": "images/chords/Ukulele_DsharpEflat.png",
			 "imageUrl3": "images/chords/Ukulele_F.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 3,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_F.png",
			 "imageUrl3": "images/chords/Ukulele_G.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 4,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_G.png",
			 "imageUrl3": "images/chords/Ukulele_A.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 5,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_A.png",
			 "imageUrl3": "images/chords/Ukulele_B.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 6,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl3": "images/chords/Ukulele_C.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 7,
			 "progName": "I-IV-V",
			 "progTitle": "Folk Rock and Western",
			 "progStyle": "Folk 1",			 
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_C.png",
			 "imageUrl3": "images/chords/Ukulele_D.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},			
			{"progId": 8,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_D.png",
			 "imageUrl3": "images/chords/Ukulele_E7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 9,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl2": "images/chords/Ukulele_DsharpEflat.png",
			 "imageUrl3": "images/chords/Ukulele_F7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 10,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_F.png",
			 "imageUrl3": "images/chords/Ukulele_G7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 11,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_G.png",
			 "imageUrl3": "images/chords/Ukulele_A7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 12,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_A.png",
			 "imageUrl3": "images/chords/Ukulele_B7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 13,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl3": "images/chords/Ukulele_C7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 14,
			 "progName": "I-IV-V7",
			 "progTitle": "The Heart of the Blues",
			 "progStyle": "Blues 1",			 
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "IV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_C.png",
			 "imageUrl3": "images/chords/Ukulele_D7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},			
			{"progId": 15,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "A",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "V7",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_Am.png",
			 "imageUrl2": "images/chords/Ukulele_Dm.png",
			 "imageUrl3": "images/chords/Ukulele_E7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 16,
			 "progName": "i-iV-V7",
			 "progStyle": "Blues 2",
			 "progTitle": "The Minor Blues",
			 "chordGroup": "B",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_Bm.png",
			 "imageUrl2": "images/chords/Ukulele_Em.png",
			 "imageUrl3": "images/chords/Ukulele_F7sharpG7flat.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 17,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "C",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl2": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl3": "images/chords/Ukulele_G7sharpA7flat.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 18,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "D",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_Dm.png",
			 "imageUrl2": "images/chords/Ukulele_Gm.png",
			 "imageUrl3": "images/chords/Ukulele_A7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 19,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "E",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_Em.png",
			 "imageUrl2": "images/chords/Ukulele_Am.png",
			 "imageUrl3": "images/chords/Ukulele_B7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 20,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "F",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl2": "images/chords/Ukulele_Bm.png",
			 "imageUrl3": "images/chords/Ukulele_C7sharpD7flat.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 21,
			 "progName": "i-iV-V7",
			 "progTitle": "The Minor Blues",
			 "progStyle": "Blues 2",
			 "chordGroup": "G",
			 "image1Title": "i",
			 "image2Title": "iV",
			 "image3Title": "VII",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_Gm.png",
			 "imageUrl2": "images/chords/Ukulele_Cm.png",
			 "imageUrl3": "images/chords/Ukulele_D7.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},		
			{"progId": 22,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Am.png",
			 "imageUrl2": "images/chords/Ukulele_F7sharpG7flat.png",
			 "imageUrl3": "images/chords/Ukulele_B7.png",
			 "imageUrl4": "images/chords/Ukulele_E7.png"
			},
			{"progId": 23,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl2": "images/chords/Ukulele_G7.png",
			 "imageUrl3": "images/chords/Ukulele_C7.png",
			 "imageUrl4": "images/chords/Ukulele_F7.png"
			},
			{"progId": 24,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_A7.png",
			 "imageUrl3": "images/chords/Ukulele_D7.png",
			 "imageUrl4": "images/chords/Ukulele_G7.png"
			},
			{"progId": 25,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_B7.png",
			 "imageUrl3": "images/chords/Ukulele_E7.png",
			 "imageUrl4": "images/chords/Ukulele_A7.png"
			},
			{"progId": 26,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_C7sharpD7flat.png",
			 "imageUrl3": "images/chords/Ukulele_F7sharpG7flat.png",
			 "imageUrl4": "images/chords/Ukulele_B7.png"
			},
			{"progId": 27,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_D7.png",
			 "imageUrl3": "images/chords/Ukulele_G7.png",
			 "imageUrl4": "images/chords/Ukulele_C7.png"
			},
			{"progId": 28,
			 "progName": "I-VI7-II7-V7",
			 "progTitle": "30s and 40s Swing",
			 "progStyle": "Jazz 1",
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "VI7",
			 "image3Title": "II7",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_E7.png",
			 "imageUrl3": "images/chords/Ukulele_A7.png",
			 "imageUrl4": "images/chords/Ukulele_D7.png"
			},
			{"progId": 29,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl3": "images/chords/Ukulele_D.png",
			 "imageUrl4": "images/chords/Ukulele_E.png"
			},
			{"progId": 30,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl2": "images/chords/Ukulele_Gm.png",
			 "imageUrl3": "images/chords/Ukulele_DsharpEflat.png",
			 "imageUrl4": "images/chords/Ukulele_F.png"
			},
			{"progId": 31,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_Am.png",
			 "imageUrl3": "images/chords/Ukulele_F.png",
			 "imageUrl4": "images/chords/Ukulele_G.png"
			},
			{"progId": 32,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_Bm.png",
			 "imageUrl3": "images/chords/Ukulele_G.png",
			 "imageUrl4": "images/chords/Ukulele_A.png"
			},
			{"progId": 33,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl3": "images/chords/Ukulele_A.png",
			 "imageUrl4": "images/chords/Ukulele_B.png"
			},
			{"progId": 34,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_Dm.png",
			 "imageUrl3": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl4": "images/chords/Ukulele_C.png"
			},																								
			{"progId": 35,
			 "progName": "I-vi-IV-V",
			 "progTitle": "50s and 60s Soft Rock",
			 "progStyle": "Ballad 1",
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_Em.png",
			 "imageUrl3": "images/chords/Ukulele_C.png",
			 "imageUrl4": "images/chords/Ukulele_D.png"
			},
			{"progId": 36,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl3": "images/chords/Ukulele_Bm.png",
			 "imageUrl4": "images/chords/Ukulele_E.png"
			},
			{"progId": 37,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl2": "images/chords/Ukulele_Gm.png",
			 "imageUrl3": "images/chords/Ukulele_Cm.png",
			 "imageUrl4": "images/chords/Ukulele_F.png"
			},
			{"progId": 38,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_Am.png",
			 "imageUrl3": "images/chords/Ukulele_Dm.png",
			 "imageUrl4": "images/chords/Ukulele_G.png"
			},
			{"progId": 39,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_Bm.png",
			 "imageUrl3": "images/chords/Ukulele_Em.png",
			 "imageUrl4": "images/chords/Ukulele_A.png"
			},
			{"progId": 40,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl3": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl4": "images/chords/Ukulele_B.png"
			},
			{"progId": 41,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_Dm.png",
			 "imageUrl3": "images/chords/Ukulele_Gm.png",
			 "imageUrl4": "images/chords/Ukulele_C.png"
			},
			{"progId": 42,
			 "progName": "I-vi-ii-V",
			 "progTitle": "50s Ballad",
			 "progStyle": "Ballad 2",
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "ii",
			 "image4Title": "V",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_Em.png",
			 "imageUrl3": "images/chords/Ukulele_Am.png",
			 "imageUrl4": "images/chords/Ukulele_D.png"
			},
			{"progId": 43,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "A",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Am.png",
			 "imageUrl2": "images/chords/Ukulele_CsharpDflat.png",
			 "imageUrl3": "images/chords/Ukulele_F.png",
			 "imageUrl4": "images/chords/Ukulele_E7.png"
			},
			{"progId": 44,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "B",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Bm.png",
			 "imageUrl2": "images/chords/Ukulele_DsharpEflat.png",
			 "imageUrl3": "images/chords/Ukulele_G.png",
			 "imageUrl4": "images/chords/Ukulele_F7sharpG7flat.png"
			},
			{"progId": 45,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "C",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Cm.png",
			 "imageUrl2": "images/chords/Ukulele_E.png",
			 "imageUrl3": "images/chords/Ukulele_GsharpAflat.png",
			 "imageUrl4": "images/chords/Ukulele_G7.png"
			},
			{"progId": 46,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "D",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Dm.png",
			 "imageUrl2": "images/chords/Ukulele_FsharpGflat.png",
			 "imageUrl3": "images/chords/Ukulele_Em.png",
			 "imageUrl4": "images/chords/Ukulele_A7.png"
			},
			{"progId": 47,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "E",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Em.png",
			 "imageUrl2": "images/chords/Ukulele_GsharpAflat.png",
			 "imageUrl3": "images/chords/Ukulele_C.png",
			 "imageUrl4": "images/chords/Ukulele_B7.png"
			},
			{"progId": 48,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "F",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Fm.png",
			 "imageUrl2": "images/chords/Ukulele_A.png",
			 "imageUrl3": "images/chords/Ukulele_CsharpDflat.png",
			 "imageUrl4": "images/chords/Ukulele_C7.png"
			},
			{"progId": 49,
			 "progName": "i-III-bVI-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  1",
			 "chordGroup": "G",
			 "image1Title": "i",
			 "image2Title": "III",
			 "image3Title": "bVI",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_Gm.png",
			 "imageUrl2": "images/chords/Ukulele_B.png",
			 "imageUrl3": "images/chords/Ukulele_DsharpEflat.png",
			 "imageUrl4": "images/chords/Ukulele_D7.png"
			},
			{"progId": 50,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl3": "images/chords/Ukulele_D.png",
			 "imageUrl4": "images/chords/Ukulele_E7.png"
			},
			{"progId": 51,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_B.png",
			 "imageUrl2": "images/chords/Ukulele_GmsharpAmflat.png",
			 "imageUrl3": "images/chords/Ukulele_E.png",
			 "imageUrl4": "images/chords/Ukulele_F7sharpG7flat.png"
			},
			{"progId": 52,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_Am.png",
			 "imageUrl3": "images/chords/Ukulele_F.png",
			 "imageUrl4": "images/chords/Ukulele_G7.png"
			},
			{"progId": 53,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_Bm.png",
			 "imageUrl3": "images/chords/Ukulele_G.png",
			 "imageUrl4": "images/chords/Ukulele_A7.png"
			},
			{"progId": 54,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl3": "images/chords/Ukulele_A.png",
			 "imageUrl4": "images/chords/Ukulele_B7.png"
			},
			{"progId": 55,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_Dm.png",
			 "imageUrl3": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl4": "images/chords/Ukulele_C7.png"
			},
			{"progId": 56,
			 "progName": "I-vi-IV-V7",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  2",
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "vi",
			 "image3Title": "IV",
			 "image4Title": "V7",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_Em.png",
			 "imageUrl3": "images/chords/Ukulele_C.png",
			 "imageUrl4": "images/chords/Ukulele_D7.png"
			},
			{"progId": 57,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "A",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_A.png",
			 "imageUrl2": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl3": "images/chords/Ukulele_Bm.png",
			 "imageUrl4": "images/chords/Ukulele_Bm.png"
			},
			{"progId": 58,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "B",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_B.png",
			 "imageUrl2": "images/chords/Ukulele_DmsharpEmflat.png",
			 "imageUrl3": "images/chords/Ukulele_CmsharpDmflat.png",
			 "imageUrl4": "images/chords/Ukulele_CmsharpDmflat.png"
			},
			{"progId": 59,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "C",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_C.png",
			 "imageUrl2": "images/chords/Ukulele_Em.png",
			 "imageUrl3": "images/chords/Ukulele_Dm.png",
			 "imageUrl4": "images/chords/Ukulele_Dm.png"
			},
			{"progId": 60,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "D",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_D.png",
			 "imageUrl2": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl3": "images/chords/Ukulele_Em.png",
			 "imageUrl4": "images/chords/Ukulele_Em.png"
			},
			{"progId": 62,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "E",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_E.png",
			 "imageUrl2": "images/chords/Ukulele_GmsharpAmflat.png",
			 "imageUrl3": "images/chords/Ukulele_FmsharpGmflat.png",
			 "imageUrl4": "images/chords/Ukulele_FmsharpGmflat.png"
			},
			{"progId": 63,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "F",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_F.png",
			 "imageUrl2": "images/chords/Ukulele_Am.png",
			 "imageUrl3": "images/chords/Ukulele_Gm.png",
			 "imageUrl4": "images/chords/Ukulele_Gm.png"
			},
			{"progId": 64,
			 "progName": "I-iii-ii-ii",
			 "progTitle": "Rhythm and Blues",
			 "progStyle": "R&B  3",
			 "chordGroup": "G",
			 "image1Title": "I",
			 "image2Title": "iii",
			 "image3Title": "ii",
			 "image4Title": "ii",
			 "imageUrl1": "images/chords/Ukulele_G.png",
			 "imageUrl2": "images/chords/Ukulele_Bm.png",
			 "imageUrl3": "images/chords/Ukulele_Am.png",
			 "imageUrl4": "images/chords/Ukulele_Am.png"
			},
			{"progId": 65,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "A",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_B7.png",
			 "imageUrl2": "images/chords/Ukulele_E7.png",
			 "imageUrl3": "images/chords/Ukulele_A.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 66,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "B",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_C7sharpD7flat.png",
			 "imageUrl2": "images/chords/Ukulele_F7sharpG7flat.png",
			 "imageUrl3": "images/chords/Ukulele_B.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 67,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "C",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_D7.png",
			 "imageUrl2": "images/chords/Ukulele_G7.png",
			 "imageUrl3": "images/chords/Ukulele_C.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 68,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "D",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_E7.png",
			 "imageUrl2": "images/chords/Ukulele_A7.png",
			 "imageUrl3": "images/chords/Ukulele_D.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 69,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "E",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_F7sharpG7flat.png",
			 "imageUrl2": "images/chords/Ukulele_B7.png",
			 "imageUrl3": "images/chords/Ukulele_E.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 70,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "F",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_G7.png",
			 "imageUrl2": "images/chords/Ukulele_C7.png",
			 "imageUrl3": "images/chords/Ukulele_F.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			},
			{"progId": 71,
			 "progName": "II7-V7-I",
			 "progTitle": "Hawaiian",
			 "progStyle": "Aloha",			 
			 "chordGroup": "G",
			 "image1Title": "II7",
			 "image2Title": "V7",
			 "image3Title": "I",
			 "image4Title": "Ukulele_Empty",
			 "imageUrl1": "images/chords/Ukulele_A7.png",
			 "imageUrl2": "images/chords/Ukulele_D7.png",
			 "imageUrl3": "images/chords/Ukulele_G.png",
			 "imageUrl4": "images/chords/Ukulele_Empty.png"
			}																								
		];

		//major pentatonic patterns collection		
		var improv1 = [
			{"patternId": 1,
			 "patternName": "1st Position",
			 "patternTitle": "A Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "A",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMaj1.png",
			},
			{"patternId": 2,
			 "patternName": "2nd Position",
			 "patternTitle": "A Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "A",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMaj2.png",
			},
			{"patternId": 3,
			 "patternName": "3rd Position",
			 "patternTitle": "A Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "A",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMaj3.png",
			},
			{"patternId": 4,
			 "patternName": "4th Position",
			 "patternTitle": "A Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "A",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMaj4.png",
			},
			{"patternId": 5,
			 "patternName": "5th Position",
			 "patternTitle": "A Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "A",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMaj5.png",
			},
			{"patternId": 6,
			 "patternName": "1st Position",
			 "patternTitle": "B Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "B",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMaj1.png",
			},
			{"patternId": 7,
			 "patternName": "2nd Position",
			 "patternTitle": "B Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "B",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMaj2.png",
			},
			{"patternId": 8,
			 "patternName": "3rd Position",
			 "patternTitle": "B Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "B",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMaj3.png",
			},
			{"patternId": 9,
			 "patternName": "4th Position",
			 "patternTitle": "B Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "B",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMaj4.png",
			},
			{"patternId": 10,
			 "patternName": "5th Position",
			 "patternTitle": "B Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "B",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMaj5.png",
			},
			{"patternId": 11,
			 "patternName": "1st Position",
			 "patternTitle": "C Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "C",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMaj1.png",
			},
			{"patternId": 12,
			 "patternName": "2nd Position",
			 "patternTitle": "C Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "C",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMaj2.png",
			},
			{"patternId": 13,
			 "patternName": "3rd Position",
			 "patternTitle": "C Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "C",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMaj3.png",
			},
			{"patternId": 14,
			 "patternName": "4th Position",
			 "patternTitle": "C Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "C",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMaj4.png",
			},
			{"patternId": 15,
			 "patternName": "5th Position",
			 "patternTitle": "C Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "C",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMaj5.png",
			},
			{"patternId": 16,
			 "patternName": "1st Position",
			 "patternTitle": "D Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "D",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMaj1.png",
			},
			{"patternId": 17,
			 "patternName": "2nd Position",
			 "patternTitle": "D Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "D",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMaj2.png",
			},
			{"patternId": 18,
			 "patternName": "3rd Position",
			 "patternTitle": "D Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "D",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMaj3.png",
			},
			{"patternId": 19,
			 "patternName": "4th Position",
			 "patternTitle": "D Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "D",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMaj4.png",
			},
			{"patternId": 20,
			 "patternName": "5th Position",
			 "patternTitle": "D Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "D",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMaj5.png",
			},
			{"patternId": 21,
			 "patternName": "1st Position",
			 "patternTitle": "E Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "E",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMaj1.png",
			},
			{"patternId": 22,
			 "patternName": "2nd Position",
			 "patternTitle": "E Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "E",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMaj2.png",
			},
			{"patternId": 23,
			 "patternName": "3rd Position",
			 "patternTitle": "E Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "E",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMaj3.png",
			},
			{"patternId": 24,
			 "patternName": "4th Position",
			 "patternTitle": "E Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "E",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMaj4.png",
			},
			{"patternId": 25,
			 "patternName": "5th Position",
			 "patternTitle": "E Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "E",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMaj5.png",
			},
			{"patternId": 26,
			 "patternName": "1st Position",
			 "patternTitle": "F Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "F",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMaj1.png",
			},
			{"patternId": 27,
			 "patternName": "2nd Position",
			 "patternTitle": "F Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "F",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMaj2.png",
			},
			{"patternId": 28,
			 "patternName": "3rd Position",
			 "patternTitle": "F Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "F",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMaj3.png",
			},
			{"patternId": 29,
			 "patternName": "4th Position",
			 "patternTitle": "F Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "F",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMaj4.png",
			},
			{"patternId": 30,
			 "patternName": "5th Position",
			 "patternTitle": "F Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "F",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMaj5.png",
			},
			{"patternId": 31,
			 "patternName": "1st Position",
			 "patternTitle": "G Major Pentatonic",
			 "patternStyle": "1",			 
			 "chordGroup": "G",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMaj1.png",
			},
			{"patternId": 32,
			 "patternName": "2nd Position",
			 "patternTitle": "G Major Pentatonic",
			 "patternStyle": "2",			 
			 "chordGroup": "G",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMaj2.png",
			},
			{"patternId": 33,
			 "patternName": "3rd Position",
			 "patternTitle": "G Major Pentatonic",
			 "patternStyle": "3",			 
			 "chordGroup": "G",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMaj3.png",
			},
			{"patternId": 34,
			 "patternName": "4th Position",
			 "patternTitle": "G Major Pentatonic",
			 "patternStyle": "4",			 
			 "chordGroup": "G",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMaj4.png",
			},
			{"patternId": 35,
			 "patternName": "5th Position",
			 "patternTitle": "G Major Pentatonic",
			 "patternStyle": "5",			 
			 "chordGroup": "G",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMaj5.png",
			},
			{"patternId": 36,
			 "patternName": "1st Position",
			 "patternTitle": "A Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "A",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMin1.png",
			},
			{"patternId": 37,
			 "patternName": "2nd Position",
			 "patternTitle": "A Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "A",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMin2.png",
			},
			{"patternId": 38,
			 "patternName": "3rd Position",
			 "patternTitle": "A Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "A",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMin3.png",
			},
			{"patternId": 39,
			 "patternName": "4th Position",
			 "patternTitle": "A Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "A",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMin4.png",
			},
			{"patternId": 40,
			 "patternName": "5th Position",
			 "patternTitle": "A Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "A",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_AMin5.png",
			},
			{"patternId": 41,
			 "patternName": "1st Position",
			 "patternTitle": "B Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "B",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMin1.png",
			},
			{"patternId": 42,
			 "patternName": "2nd Position",
			 "patternTitle": "B Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "B",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMin2.png",
			},
			{"patternId": 43,
			 "patternName": "3rd Position",
			 "patternTitle": "B Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "B",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMin3.png",
			},
			{"patternId": 44,
			 "patternName": "4th Position",
			 "patternTitle": "B Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "B",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMin4.png",
			},
			{"patternId": 45,
			 "patternName": "5th Position",
			 "patternTitle": "B Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "B",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_BMin5.png",
			},
			{"patternId": 46,
			 "patternName": "1st Position",
			 "patternTitle": "C Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "C",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMin1.png",
			},
			{"patternId": 47,
			 "patternName": "2nd Position",
			 "patternTitle": "C Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "C",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMin2.png",
			},
			{"patternId": 48,
			 "patternName": "3rd Position",
			 "patternTitle": "C Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "C",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMin3.png",
			},
			{"patternId": 49,
			 "patternName": "4th Position",
			 "patternTitle": "C Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "C",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMin4.png",
			},
			{"patternId": 50,
			 "patternName": "5th Position",
			 "patternTitle": "C Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "C",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_CMin5.png",
			},
			{"patternId": 51,
			 "patternName": "1st Position",
			 "patternTitle": "D Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "D",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMin1.png",
			},
			{"patternId": 52,
			 "patternName": "2nd Position",
			 "patternTitle": "D Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "D",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMinj2.png",
			},
			{"patternId": 53,
			 "patternName": "3rd Position",
			 "patternTitle": "D Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "D",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMin3.png",
			},
			{"patternId": 54,
			 "patternName": "4th Position",
			 "patternTitle": "D Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "D",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMin4.png",
			},
			{"patternId": 55,
			 "patternName": "5th Position",
			 "patternTitle": "D Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "D",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_DMin5.png",
			},
			{"patternId": 56,
			 "patternName": "1st Position",
			 "patternTitle": "E Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "E",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin1.png",
			},
			{"patternId": 57,
			 "patternName": "2nd Position",
			 "patternTitle": "E Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "E",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin2.png",
			},
			{"patternId": 58,
			 "patternName": "3rd Position",
			 "patternTitle": "E Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "E",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin3.png",
			},
			{"patternId": 59,
			 "patternName": "4th Position",
			 "patternTitle": "E Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "E",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin4.png",
			},
			{"patternId": 60,
			 "patternName": "5th Position",
			 "patternTitle": "E Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "E",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin5.png",
			},
			{"patternId": 61,
			 "patternName": "1st Position",
			 "patternTitle": "F Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "F",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMin1.png",
			},
			{"patternId": 62,
			 "patternName": "2nd Position",
			 "patternTitle": "F Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "F",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMin2.png",
			},
			{"patternId": 63,
			 "patternName": "3rd Position",
			 "patternTitle": "F Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "F",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMin3.png",
			},
			{"patternId": 64,
			 "patternName": "4th Position",
			 "patternTitle": "F Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "F",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMin4.png",
			},
			{"patternId": 65,
			 "patternName": "5th Position",
			 "patternTitle": "F Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "F",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_FMin5.png",
			},
			{"patternId": 66,
			 "patternName": "1st Position",
			 "patternTitle": "G Minor Pentatonic",
			 "patternStyle": "m1",			 
			 "chordGroup": "G",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMin1.png",
			},
			{"patternId": 67,
			 "patternName": "2nd Position",
			 "patternTitle": "G Minor Pentatonic",
			 "patternStyle": "m2",			 
			 "chordGroup": "G",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMin2.png",
			},
			{"patternId": 68,
			 "patternName": "3rd Position",
			 "patternTitle": "G Minor Pentatonic",
			 "patternStyle": "m3",			 
			 "chordGroup": "G",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMin3.png",
			},
			{"patternId": 69,
			 "patternName": "4th Position",
			 "patternTitle": "G Minor Pentatonic",
			 "patternStyle": "m4",			 
			 "chordGroup": "G",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMin4.png",
			},
			{"patternId": 70,
			 "patternName": "5th Position",
			 "patternTitle": "G Minor Pentatonic",
			 "patternStyle": "m5",			 
			 "chordGroup": "G",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_GMin5.png",
			}
		];

var improv2 = [
			{"patternId": 1,
			 "patternName": "1st Position",
			 "patternTitle": "Minor Pentatonic 1",
			 "patternStyle": "1",			 
			 "chordGroup": "A",
			 "image1Title": "1st Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin1.png",
			},
			{"patternId": 2,
			 "patternName": "2nd Position",
			 "patternTitle": "Minor Pentatonic 2",
			 "patternStyle": "2",			 
			 "chordGroup": "A",
			 "image1Title": "2nd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin2.png",
			},
			{"patternId": 3,
			 "patternName": "3rd Position",
			 "patternTitle": "Minor Pentatonic 3",
			 "patternStyle": "3",			 
			 "chordGroup": "A",
			 "image1Title": "3rd Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin3.png",
			},
			{"patternId": 4,
			 "patternName": "4th Position",
			 "patternTitle": "Minor Pentatonic 4",
			 "patternStyle": "4",			 
			 "chordGroup": "A",
			 "image1Title": "4th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin4.png",
			},
			{"patternId": 5,
			 "patternName": "5th Position",
			 "patternTitle": "Minor Pentatonic 5",
			 "patternStyle": "5",			 
			 "chordGroup": "A",
			 "image1Title": "5th Position",
			 "imageUrl1": "images/patterns/Pentatonic_EMin5.png",
			}
		];
		//tips collection
		var tips = [
			{"tipId": 1,
			 "tipName": "Ukulele Care",
			 "tipDescription": "Keeping your Uke in good shape.",
			 "tipInfo": "One of the best things you can do to keep your instrument in good shape is to play it regularly. Since it's designed to be played, the more often you use it, the better it will sound.",
			 "tipInfo1": "To keep your uke sounding good a certain amount of care and maintenance is required. Clean it after you play it. You can buy all sorts of fancy instrument-cleaning products but simply giving your ukulele a quick wipe-down with a soft cotton cloth for example a t-shirt is all you really need to do. This wipe-down prevents your sweat getting mixed with dust and messing up your uke.",
			 "tipInfo3": "Maintain the right humidity. Wood is a natural breathing material and reacts to the surrounding environment. Therefore you have to be careful if you live in a dry or wet location. If the air is very dry the wood on your uke can crack. Invest in an instrument humidifier or some Boveda packs to avoid this problem. Just put this little device in your ukulele case and it keeps the conditions more  instrument friendly. Humidifiers and Boveda packs are simple and fairly inexpensive and so if you have invested in a nice uke, the investment is certainly worthwhile. If the air is very damp it can warp. Leave a Boveda silica gel pack in the case to avoid this problem which is more likely with solid wood models. Laminated ones tend to hold up a bit better in humid conditions. Ukes quite often come with silica packs anyway but they are also cheap and easy to buy separately.",
			 "tipInfo2": "Store it properly. Even if you never take your uke out of the house, invest in a bag or case. Even the flimsiest one will give protection against dust and light dings. Temperature is actually the big issue with storage. Avoid leaving your uke in direct sunlight, in fact steer clear of heaters altogether. For instance, avoid leaving it in a hot car. Cold is less of a problem, but if you are traveling by car, carry your uke inside with you rather than sticking it in the trunk.",
			 "tipCatagory":"Instrument",
			 "tags": ["Care", "Instrument"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 2,
			 "tipName": "Finger Picking",
			 "tipDescription": "An intro to finger picking your tunes.",
			 "tipInfo": "To fingerpick your ukulele instead of strumming your fingers along the strings you pluck the strings individually.  Each of the fingers of your picking hand is allocated to a specific string.",
			 "tipInfo1": "Curl your fingers around so that they are slightly underneath the string, with the string running over the fingertip.  Try to keep your hand as relaxed as possible.  You can do one of two things with your little finger.  Proper technique dictates that you lift it up off the body of the uke, which allows you to switch quickly between picking and strumming and means that you are not dampening the soundboard of the ukulele at all.  You can however use your little finger to anchor your hand to the body, which gives your picking hand more stability.",
			 "tipInfo2": "One potential downside of sticking your little finger in the air is that after a while it tends to fall into that position naturally. You pluck the string by curling your finger further around to slightly lift then release the string. This action does not need much force. If you pluck too hard the string may vibrate against the frets and cause buzzing.",
			 "tipInfo3": "Letters are used to illustrate fingerpicking in tablature and the fingers of the picking hand are referred to as follows.  T-Thumb, I-Index finger, M-Middle finger, A-Ring finger.  These finger names appear directly beneath each note.  Where two notes are picked at the same time, they appear one on top of the other in the same configuration as the tab.",
			 "tipCatagory":"Lessons",
			 "tags": ["Skills", "Picking"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 3,
			 "tipName": "Strumming",
			 "tipDescription": "A few basics on basic strumming technique.",
			 "tipInfo": "It is important to practice any strumming pattern with a metronome, drum track or pre-recorded song if you want to learn to play in time. Tap your foot along with the beat.",
			 "tipInfo1": "Keep your strumming arm swinging up and down in a steady motion whether or not you're hitting the strings. If you are playing with music notation or tab, the strumming pattern may be indicated using up and down symbols to indicate the suggested strumming pattern. Certain strumming patterns are common with particular styles of music such as Hawaiian or folk for instance. ",
			 "tipInfo2": "Make sure that you count when you play, it will help you a lot going forward when subdividing the beats. If you are playing along with a pre-recorded tune that includes drums, the 2nd and 4th beat is when the snare drum is typically played. Listening for this can help you locate and stay on the beat in most songs.",
			 "tipInfo3": "Tap your foot on the downstrokes, this will help you with your internal clock. Don't worry about chord changes for now, just grab a basic chord and first get comfortable with the strumming pattern. As you practice, be sure you can play along with the beat consistently as you tap your foot. Only add a chord change once you have the strumming pattern sorted properly. Once you are comfortable with this approach, you'll be more prepared to play along with other musicians in a jam session.",
			 "tipCatagory":"Lessons",
			 "tags": ["Skills", "Strumming"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 4,
			 "tipName": "Changing Strings",
			 "tipDescription": "Some ideas to consider when you change your strings.",
			 "tipInfo": "Always give your new strings a stretch when you put them on.  When the string is in tune, gently pull it away from the body and give it two or three little tugs. Repeat until it stays in tune.",
			 "tipInfo1": "If you are in a massive hurry to change strings, such as finding they are damaged or sound horrible just before a performance, you can just cut them without too much risk. It is a better idea though to unspool the tuning pegs until you have enough slack to pull the strings off. This is better for long term health of your instrument.",
			 "tipInfo2": "Putting on a high quality set of strings is the quickest and cheapest way to improve the sound of any ukulele.  Two recommended brands are Aquila and Worth. Be sure to get strings that are designd for your instrument. For instance, if you have a soprana Ukelele get soprano strings. If you aren't sure, take it with you to your local music store and ask for help.",
			 "tipInfo3": "Never put steel strings on a uke. The tension will ruin the instrument. Some common types of strings are Nyglut or Fluoro-Carbon ",
			 "tipCatagory":"Instrument",
			 "tags": ["Care", "Instrument", "Strings"],  	
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 5,
			 "tipName": "Using a Capo",
			 "tipDescription": "Find out why using a capo can be cool.",
			 "tipInfo": "A capo straps around the neck of your uke and holds down the strings. For example, putting the capo on the second fret raises each string by one step so C becomes D.",
			 "tipInfo1": "Capos come in a couple of different types. Most capos are the elastic type. These tend to be particularly good because they are flexible enough to handle the various sizes of ukes. The other type is the lever capo.  The advantage of using lever capos is they can be quickly put on and taken off and they tend to create less buzz from the strings. You may notice this the type used by most guitarists. When you put the capo on, check your tuning again and make minor adjustments if needed. Sometimes the pressure from the capo tends to bend the strings a bit and pull it out of tune.",
			 "tipInfo2": "Mandolin and banjo capos actually work well for most ukes. Your local music store or amazon will typically have these in stock.",
			 "tipInfo3": "You can change from C-tuning GCEA to D-tuning ADF#B simply by putting the capo on the second fret. This is a pretty common practice with guitar players and will help you in jam sesions.",
			 "tipCatagory":"Accessories",
			 "tags": ["Skills", "Picking"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 6,
			 "tipName": "Choosing a Case",
			 "tipDescription": "All cases are not created equal.",
			 "tipInfo": "Uke cases typically come in three varieties - Gig bags, Soft Cases, and Hardshell Cases.  Unfortunately, the harder the case, the less actual storage space you tend to get.",
			 "tipInfo1": "Gig bags are soft bags the keep the dust off your ukulele but don't actually offer much protection that that.",
			 "tipInfo2": "Soft cases have stiffer sides than gig bags and are usually padded. They give your uke a certain amount of protection from knocks.",
			 "tipInfo3": "Hard cases are perfect for traveling musicians and anyone who may be a bit clumsy and offer the most protection. Many hard cases have just a small compartment under the neck, which is a hangover from the design of guitar cases. In a uke case this results in just enough room to store change for the the accessories you want.  This means you may also want to bring a bag for extra strings, cleaning cloth and tuner etc.",
			 "tipCatagory":"Accessories",
			 "tags": ["Skills", "Strumming"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 7,
			 "tipName": "Styles: R&B",
			 "tipDescription": "A few tips on how to play Rhythm and Blues.",
			 "tipInfo": "Contemporary R&B combines elements of Rhythm and Blues, Soul, Funk, Pop, Hip-hop and Dance. Popular R&B vocalists include Michael Jackson, R. Kelly and Stevie Wonder.",
			 "tipInfo1": "One thing that's cool to do in these styles is to choose a regular progression like I-IV-V, but give ALL the chords the same quality and extension, for example CMaj9 - FMaj9 - GMaj9 - CMaj9 or even Cm9 - Fm9 - Gm9 - Cm9.",
			 "tipInfo2": "Another common idea is to use hip sounding slash chords such as CMaj9 - FMaj9/A - GMaj9/B - CMaj9, for an 80s sound like Mariah and Whitney. The note after the slash indicates the bass note of the chord above it. This a common technique guitar and keyboard players use to vary the sound of their chords and can offer a nice harmonic contrast especially when playing with other musicians.",
			 "tipInfo3": "It is also common to stick to flat keys - Ab, Eb, Bb etc. as these tend to sound less cliche than regular guitar keys like A, E, D. Basically, try to avoid guitar keys like the plague, and lean to the more jazz sounding flat keys for an authentic R&B feel.",
			 "tipCatagory":"Styles",
			 "tags": ["Styles"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 8,
			 "tipName": "Uke History",
			 "tipDescription": "Some interesting historical facts about the Ukulele.",
			 "tipInfo": "The Ukelele is the beloved instrument of Hawaiians and laid back pluckers of happy tunes. So easy to pick up and learn, but really hard to put back down once you learn a few songs.",
			 "tipInfo1": "George Harrison of the Beatles, was said to have traveled with 2 ukes, one for himself and another for anyone he happened to be hanging out with. Jimi Hendrix also enjoyed the little instrument. Seeing Hendrix play a uke would be interesting to say the least.",
			 "tipInfo2": "The Ukulele originated in the 19th century as a Hawaiian interpretation of the machete, a small guitar-like instrument related to the cavaquinho, timple, braguinha and the rajao, taken to Hawaii by Portuguese immigrants. It gained great popularity elsewhere in the United States during the early 20th century, and from there spread internationally.",
			 "tipInfo3": "The Ukulele is commonly associated with music from Hawaii where the name roughly translates as jumping flea, perhaps because of the movement of the players fingers. Legend attributes it to the nickname of the Englishman Edward William Purvis, one of King Kalākaua's officers, because of his small size, fidgety manner, and playing expertise.",
			 "tipCatagory":"History",
			 "tags": ["History", "Trivia"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 9,
			 "tipName": "About Tabs",
			 "tipDescription": "An overview on how to read tabs.",
			 "tipInfo": "Tablature is used to represent music for a specific instrument and is an alternative to standard notation that is easier to read. Tabs show you on which string to play a particular note.",
			 "tipInfo1": "Tablature has a couple of advantages. First, it is much easier to learn to read than standard notation and much more accessible for those without formal musical training. Second, it tells you on which string to play a particular note. This is particularly important on the ukulele as the strings are tuned so close together and the way in which you play them can change how easy it is to play a tune a great deal.",
			 "tipInfo2": "Each of the horizontal lines represents a string on the ukulele. However, they are upside down from what you might expect. The top line of the tab is the A string - the one that is closest to the floor when you are playing. The line below that is the E string, the line below that is the C string and the bottom line of the tab is G string.",
			 "tipInfo3": "The numbers that appear on the tab indicate which string to play and what fret to play it at. A number 1 means that the string indicated on the tab should be played at the first fret. Playing the E string at the first fret gives us an F note. Open strings, meaning strings played without fretting a note at all, are indicated by a 0.",
			 "tipCatagory":"Lessons",
			 "tags": ["Lessons", "Tabs"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			},
			{"tipId": 10,
			 "tipName": "Shorthand",
			 "tipDescription": "Learn how to write tunes in shorthand.",
			 "tipInfo": "When you're at the beach or on the trail, writing tunes in shorthand is a great idea. Basically it's just writing lyrics with the chords inserted where they are played.",
			 "tipInfo1": "Let's say you're writing or sharing a song that has the following chords - D-G-A-C. The lyrics for our song are - I'm a freeborn man of the travelling people, Got no fixed abode with nomads I am numbered, Country lanes and by ways were always my way, I've never fancied being lumbered. See Tip 2 for the shorthand version.",
			 "tipInfo2": "The chords for this song are D-G-A-C so we would write the shorthand version as follows- I’m [D] a freeborn man of the [G] travelling peop[A]le, [D] Got no fixed a[A]bode with nomads I am [D] numbered, [A] Country lanes and by ways were [D] always [G] my [D] way, I've [G] never [D] fancied [C] being lum[D]bered.",
			 "tipInfo3": "Shorthand saves time when you are in a rush or just writing a song without wanting to use tablature or formal notation.",
			 "tipCatagory":"Songwriting",
			 "tags": ["Songwriting", "ProTips"],
			 "imageUrl": "images/tips/ukeIMG_2B.jpg",
			 "imageUrl2": "images/ukelele_humifier.jpg",
			 "imageUrl3": "images/ukelele_humifier.jpg",
			 "imageUrl4": "images/ukelele_humifier.jpg"
			}
		]; 

		//themes collection
		var themes = [
			{"themeId": 1,
			 "themeName": "Zhen Sky",
			 "themeInfo": "The calming vibe of Zhen.",
			 "themeCSS": "css/zhenSky.css",
			 "themeLayout": "zhenSky",
			 "tags": ["theme", "blue", "Night"],
			 "imageUrl": "images/themes/ZhenSkyThumb.png"
			},
			{"themeId": 2,
			 "themeName": "Beach Vacation",
			 "themeInfo": "Life's a beach and then you fry.",
			 "themeCSS": "css/beachVacation.css",
			 "themeLayout": "beachVacation",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/BeachVacationThumb.png"
			},
			{"themeId": 3,
			 "themeName": "Black Light",
			 "themeInfo": "When you're groovy man",
			 "themeCSS": "css/blackLight.css",
			 "themeLayout": "Black Light",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/BlackLightThumb.png"
			},
			{"themeId": 4,
			 "themeName": "Pueblo Clay",
			 "themeInfo": "South West by South West.",
			 "themeCSS": "css/puebloClay.css",
			 "themeLayout": "puebloClay",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/PuebloClayThumb.png"
			},
			{"themeId": 5,
			 "themeName": "Cloud Chaser",
			 "themeInfo": "There's something in the air.",
			 "themeCSS": "css/vaped.css",
			 "themeLayout": "vaped",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/VapedThumb.png"
			},
			{"themeId": 6,
			 "themeName": "Green Thumb",
			 "themeInfo": "A little green is a good thing.",
			 "themeCSS": "css/greenThumb.css",
			 "themeLayout": "Green Thumb",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/GreenThumb.png"
			},
			{"themeId": 7,
			 "themeName": "Maui Sunset",
			 "themeInfo": "Sun is setting.",
			 "themeCSS": "css/sunSet.css",
			 "themeLayout": "Sun Set",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/SunSetThumb.png"
			},
			{"themeId": 8,
			 "themeName": "Stage Right",
			 "themeInfo": "Give me a spot light here.",
			 "themeCSS": "css/stageRight.css",
			 "themeLayout": "Stage Right",
			 "tags": ["theme", "blue", "Day"],
			 "imageUrl": "images/themes/StageRightThumb.png"
			}
		];

		//beats collection
		var beats = [
			{"beatId": 1,
			 "beatName": "1",
			 "beatTitle": "Folk Beat 1",
			 "beatStyle": "Folk",			 
			 "beatGroup": "Folk",
			 "image1Title": "Folk Beat 1",
			 "imageUrl": "images/chords/Ukulele_A.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 2,
			 "beatName": "2",
			 "beatTitle": "Folk Beat 2",
			 "beatStyle": "Folk",			 
			 "beatGroup": "Folk",
			 "imageUrl": "images/chords/Ukulele_B.png",
			 "image1Title": "Folk Beat 2",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/bluesBeat_12barx3.m4a"
			},
			{"beatId": 3,
			 "beatName": "3",
			 "beatTitle": "Folk Beat 3",
			 "beatStyle": "Folk",			 
			 "beatGroup": "Folk",
			 "image1Title": "Folk Beat 3",
			 "imageUrl": "images/chords/Ukulele_C.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 4,
			 "beatName": "1",
			 "beatTitle": "12 Bar / 3 times",
			 "beatStyle": "Blues",			 
			 "beatGroup": "Blues",
			 "image1Title": "Blues Beat 1",
			 "imageUrl": "images/chords/Ukulele_D.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 5,
			 "beatName": "2",
			 "beatTitle": "12 Bar / 3 times",
			 "beatStyle": "Blues",			 
			 "beatGroup": "Blues",
			 "image1Title": "Blues Beat 1",
			 "imageUrl": "images/chords/Ukulele_E.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 6,
			 "beatName": "1",
			 "beatTitle": "Hawaiian Beat 1",
			 "beatStyle": "Aloha",			 
			 "beatGroup": "Hawaii",
			 "image1Title": "Hawaiian Beat 1",
			 "imageUrl": "images/chords/Ukulele_F.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 7,
			 "beatName": "2",
			 "beatTitle": "Hawaiian Beat 2",
			 "beatStyle": "Aloha",			 
			 "beatGroup": "Hawaii",
			 "image1Title": "Hawaiian Beat 2",
			 "imageUrl": "images/chords/Ukulele_G.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 8,
			 "beatName": "1",
			 "beatTitle": "Jazz Beat 1",
			 "beatStyle": "Jazz",			 
			 "beatGroup": "Jazz",
			 "image1Title": "Jazz Beat 1",
			 "imageUrl": "images/chords/Ukulele_A.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 9,
			 "beatName": "2",
			 "beatTitle": "Jazz Beat 2",
			 "beatStyle": "Jazz",			 
			 "beatGroup": "Jazz",
			 "image1Title": "Jazz Beat 2",
			 "imageUrl": "images/chords/Ukulele_AsharpBflat.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 10,
			 "beatName": "1",
			 "beatTitle": "Country Beat 1",
			 "beatStyle": "Country",			 
			 "beatGroup": "Country",
			 "image1Title": "Country Beat 1",
			 "imageUrl": "images/chords/Ukulele_C7sharpD7flat.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 11,
			 "beatName": "2",
			 "beatTitle": "Country Beat 2",
			 "beatStyle": "Country",			 
			 "beatGroup": "Country",
			 "image1Title": "Country Beat 2",
			 "imageUrl": "images/chords/Ukulele_Bsus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 12,
			 "beatName": "1",
			 "beatTitle": "Rock Beat 1",
			 "beatStyle": "Rock",			 
			 "beatGroup": "Rock",
			 "image1Title": "Rock Beat 1",
			 "imageUrl": "images/chords/Ukulele_D9sharpE9flat.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 13,
			 "beatName": "2",
			 "beatTitle": "Rock Beat 2",
			 "beatStyle": "Rock",			 
			 "beatGroup": "Rock",
			 "image1Title": "Rock Beat 2",
			 "imageUrl": "images/chords/Ukulele_E9.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 14,
			 "beatName": "1",
			 "beatTitle": "Click Track 1",
			 "beatStyle": "Click",			 
			 "beatGroup": "Click",
			 "image1Title": "Click Track 1",
			 "imageUrl": "images/chords/Ukulele_Fsus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 15,
			 "beatName": "2",
			 "beatTitle": "Click Track 2",
			 "beatStyle": "Click",			 
			 "beatGroup": "Click",
			 "image1Title": "Click Track 2",
			 "imageUrl": "images/chords/Ukulele_Gsus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 16,
			 "beatName": "1",
			 "beatTitle": "R&B Beat 1",
			 "beatStyle": "R&B",			 
			 "beatGroup": "R&B",
			 "image1Title": "R&B Beat 1",
			 "imageUrl": "images/chords/Ukulele_Asus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 17,
			 "beatName": "2",
			 "beatTitle": "R&B Beat 2",
			 "beatStyle": "R&B",			 
			 "beatGroup": "R&B",
			 "image1Title": "R&B Beat 2",
			 "imageUrl": "images/chords/Ukulele_Bsus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 18,
			 "beatName": "1",
			 "beatTitle": "Ballad Beat 1",
			 "beatStyle": "Ballad",			 
			 "beatGroup": "Ballad",
			 "image1Title": "Ballad Beat 1",
			 "imageUrl": "images/chords/Ukulele_Csus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			},
			{"beatId": 19,
			 "beatName": "2",
			 "beatTitle": "Ballad Beat 2",
			 "beatStyle": "Ballad",			 
			 "beatGroup": "Ballad",
			 "image1Title": "Ballad Beat 2",
			 "imageUrl": "images/chords/Ukulele_Dsus.png",
			 "imageUrl1": "images/beats/FolkBeat1Img.png",
			 "beatAudioUrl": "audio/beats/folkBeat_12barx3.m4a"
			}
		];		

		var productUrl = "/api/chords";
		var tipUrl = "/api/tips";
		var themeUrl = "/api/themes";
		var progUrl = "/api/progressions";
		var pattern1Url = "/api/improv1";
		var pattern2Url = "/api/improv2";
		var beatUrl = "/api/beats";		


		$httpBackend.whenGET(productUrl).respond(chords);
		$httpBackend.whenGET(tipUrl).respond(tips);
		$httpBackend.whenGET(progUrl).respond(progressions);
		$httpBackend.whenGET(pattern1Url).respond(improv1);
		$httpBackend.whenGET(pattern2Url).respond(improv2);
		$httpBackend.whenGET(themeUrl).respond(themes);
		$httpBackend.whenGET(beatUrl).respond(beats);

		var editingRegex = new RegExp(tipUrl + "/[0-9][0-9]*", '');
		
		$httpBackend.whenGET(editingRegex).respond(function (method, url, data){
			var tip = {"tipId": 0};
			var parameters = url.split('/');
			var length = parameters.length;
			var id = parameters[length - 1];

			if (id > 0){
				for (var i = 0; i < tips.length; i++){
					if(tips[i].tipId == id) {
						tip = tips[i];
						break;
					}
				};
			}
			return [200, tip, {}];
		});
/*
		$httpBackend.whenPOST(productUrl).respond(function (method, url, data){
			var product =  angular.fromJson(data);
			if (!product.productId){
				//new product Id
				product.productId = products[products.length - 1].productId + 1;
				products.push(product);
			}
			else{
				//update product
				for (var i = 0; i < products.length; i++) {
					if (products[i].productId == product.productId){
						products[i] = product;
						break;
					}
				};
			}
			return [200, product, {}];
		});
*/
/*
		var editingRegex = new RegExp(productUrl + "/[0-9][0-9]*", '');
		
		$httpBackend.whenGET(editingRegex).respond(function (method, url, data){
			var product = {"productId": 0};
			var parameters = url.split('/');
			var length = parameters.length;
			var id = parameters[length - 1];

			if (id > 0){
				for (var i = 0; i < products.length; i++){
					if(products[i].productId == id) {
						product = products[i];
						break;
					}
				};
			}
			return [200, product, {}];
		});

		$httpBackend.whenPOST(productUrl).respond(function (method, url, data){
			var product =  angular.fromJson(data);
			if (!product.productId){
				//new product Id
				product.productId = products[products.length - 1].productId + 1;
				products.push(product);
			}
			else{
				//update product
				for (var i = 0; i < products.length; i++) {
					if (products[i].productId == product.productId){
						products[i] = product;
						break;
					}
				};
			}
			return [200, product, {}];
		});
*/
		//Pass through any requests for application files
		$httpBackend.whenGET(/app/).passThrough();




	})
}());